language: node_js
node_js:
  - 0.10

sudo: false

addons:
  sauce_connect:
    username: scribe-ci
    access_key: 4be9eeed-61de-4948-b18d-f7f655e9e4b0
env:
  matrix:
  matrix:
    - BROWSER_NAME='firefox' BROWSER_VERSION='31' PLATFORM='OSX 10.6'
    - BROWSER_NAME='firefox' BROWSER_VERSION='32' PLATFORM='OSX 10.6'
    - BROWSER_NAME='firefox' BROWSER_VERSION='33' PLATFORM='OSX 10.6'
    - BROWSER_NAME='chrome' BROWSER_VERSION='35' PLATFORM='OSX 10.8'
    - BROWSER_NAME='chrome' BROWSER_VERSION='36' PLATFORM='OSX 10.8'
    - BROWSER_NAME='chrome' BROWSER_VERSION='37' PLATFORM='OSX 10.8'
    - BROWSER_NAME='chrome' BROWSER_VERSION='38' PLATFORM='OSX 10.8'
    - BROWSER_NAME='firefox' BROWSER_VERSION='33' PLATFORM='Windows 7'
    - BROWSER_NAME='chrome' BROWSER_VERSION='38' PLATFORM='Windows 7'

before_script:
  - npm install -g bower
  - bower install
script: npm test
